version: '3.3'

services:

  lds:
    image: lds-server:dev
    ports:
    - "9090:9090"
    volumes:
    - ldsconf:/lds/conf:ro
    - ldsschemas:/lds/schemas:ro
    depends_on:
    - db-neo4j
    - db-postgres

  db-neo4j:
    image: neo4j:3.5
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - ldsneo4jdb:/data
    environment:
    - NEO4J_AUTH: neo4j/PasSW0rd

  db-postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ldspostgresdb:/var/lib/postgresql/data
      - ${PWD}/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  ldspostgresdb:
  ldsneo4jdb:
  ldsconf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/conf
      o: bind
  ldsschemas:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/gsim-raml-schema/jsonschemas
      o: bind
